feign:
  client:
    default:
      dynamic-client:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

application:
  integration:
    eipa:
      url: https://eipa.udt.gov.pl
      token: 79e82e0d4033a8da9934fcb083e64326
    sink:
      url: https://httpbin.org/post

logging:
  level:
    root: INFO
    com.tomtom: TRACE
